// Code generated by mockery. DO NOT EDIT.

package mock_syncinterfaces

import mock "github.com/stretchr/testify/mock"

// EthermanGetL1Client is an autogenerated mock type for the EthermanGetL1Client type
type EthermanGetL1Client struct {
	mock.Mock
}

type EthermanGetL1Client_Expecter struct {
	mock *mock.Mock
}

func (_m *EthermanGetL1Client) EXPECT() *EthermanGetL1Client_Expecter {
	return &EthermanGetL1Client_Expecter{mock: &_m.Mock}
}

// GetL1EthereumClient provides a mock function with given fields:
func (_m *EthermanGetL1Client) GetL1EthereumClient() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetL1EthereumClient")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// EthermanGetL1Client_GetL1EthereumClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetL1EthereumClient'
type EthermanGetL1Client_GetL1EthereumClient_Call struct {
	*mock.Call
}

// GetL1EthereumClient is a helper method to define mock.On call
func (_e *EthermanGetL1Client_Expecter) GetL1EthereumClient() *EthermanGetL1Client_GetL1EthereumClient_Call {
	return &EthermanGetL1Client_GetL1EthereumClient_Call{Call: _e.mock.On("GetL1EthereumClient")}
}

func (_c *EthermanGetL1Client_GetL1EthereumClient_Call) Run(run func()) *EthermanGetL1Client_GetL1EthereumClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EthermanGetL1Client_GetL1EthereumClient_Call) Return(_a0 interface{}) *EthermanGetL1Client_GetL1EthereumClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EthermanGetL1Client_GetL1EthereumClient_Call) RunAndReturn(run func() interface{}) *EthermanGetL1Client_GetL1EthereumClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewEthermanGetL1Client creates a new instance of EthermanGetL1Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEthermanGetL1Client(t interface {
	mock.TestingT
	Cleanup(func())
}) *EthermanGetL1Client {
	mock := &EthermanGetL1Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
