// Code generated by mockery. DO NOT EDIT.

package mock_syncinterfaces

import (
	context "context"

	state "github.com/0xPolygonHermez/zkevm-node/state"
	mock "github.com/stretchr/testify/mock"
)

// L1BlockCheckerIntegrator is an autogenerated mock type for the L1BlockCheckerIntegrator type
type L1BlockCheckerIntegrator struct {
	mock.Mock
}

type L1BlockCheckerIntegrator_Expecter struct {
	mock *mock.Mock
}

func (_m *L1BlockCheckerIntegrator) EXPECT() *L1BlockCheckerIntegrator_Expecter {
	return &L1BlockCheckerIntegrator_Expecter{mock: &_m.Mock}
}

// OnCheckReorg provides a mock function with given fields: ctx, latestBlock
func (_m *L1BlockCheckerIntegrator) OnCheckReorg(ctx context.Context, latestBlock *state.Block) bool {
	ret := _m.Called(ctx, latestBlock)

	if len(ret) == 0 {
		panic("no return value specified for OnCheckReorg")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, *state.Block) bool); ok {
		r0 = rf(ctx, latestBlock)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// L1BlockCheckerIntegrator_OnCheckReorg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnCheckReorg'
type L1BlockCheckerIntegrator_OnCheckReorg_Call struct {
	*mock.Call
}

// OnCheckReorg is a helper method to define mock.On call
//   - ctx context.Context
//   - latestBlock *state.Block
func (_e *L1BlockCheckerIntegrator_Expecter) OnCheckReorg(ctx interface{}, latestBlock interface{}) *L1BlockCheckerIntegrator_OnCheckReorg_Call {
	return &L1BlockCheckerIntegrator_OnCheckReorg_Call{Call: _e.mock.On("OnCheckReorg", ctx, latestBlock)}
}

func (_c *L1BlockCheckerIntegrator_OnCheckReorg_Call) Run(run func(ctx context.Context, latestBlock *state.Block)) *L1BlockCheckerIntegrator_OnCheckReorg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*state.Block))
	})
	return _c
}

func (_c *L1BlockCheckerIntegrator_OnCheckReorg_Call) Return(_a0 bool) *L1BlockCheckerIntegrator_OnCheckReorg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *L1BlockCheckerIntegrator_OnCheckReorg_Call) RunAndReturn(run func(context.Context, *state.Block) bool) *L1BlockCheckerIntegrator_OnCheckReorg_Call {
	_c.Call.Return(run)
	return _c
}

// OnStart provides a mock function with given fields: ctx
func (_m *L1BlockCheckerIntegrator) OnStart(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for OnStart")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// L1BlockCheckerIntegrator_OnStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnStart'
type L1BlockCheckerIntegrator_OnStart_Call struct {
	*mock.Call
}

// OnStart is a helper method to define mock.On call
//   - ctx context.Context
func (_e *L1BlockCheckerIntegrator_Expecter) OnStart(ctx interface{}) *L1BlockCheckerIntegrator_OnStart_Call {
	return &L1BlockCheckerIntegrator_OnStart_Call{Call: _e.mock.On("OnStart", ctx)}
}

func (_c *L1BlockCheckerIntegrator_OnStart_Call) Run(run func(ctx context.Context)) *L1BlockCheckerIntegrator_OnStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *L1BlockCheckerIntegrator_OnStart_Call) Return(_a0 error) *L1BlockCheckerIntegrator_OnStart_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *L1BlockCheckerIntegrator_OnStart_Call) RunAndReturn(run func(context.Context) error) *L1BlockCheckerIntegrator_OnStart_Call {
	_c.Call.Return(run)
	return _c
}

// OnStartL1Sync provides a mock function with given fields: ctx
func (_m *L1BlockCheckerIntegrator) OnStartL1Sync(ctx context.Context) bool {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for OnStartL1Sync")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// L1BlockCheckerIntegrator_OnStartL1Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnStartL1Sync'
type L1BlockCheckerIntegrator_OnStartL1Sync_Call struct {
	*mock.Call
}

// OnStartL1Sync is a helper method to define mock.On call
//   - ctx context.Context
func (_e *L1BlockCheckerIntegrator_Expecter) OnStartL1Sync(ctx interface{}) *L1BlockCheckerIntegrator_OnStartL1Sync_Call {
	return &L1BlockCheckerIntegrator_OnStartL1Sync_Call{Call: _e.mock.On("OnStartL1Sync", ctx)}
}

func (_c *L1BlockCheckerIntegrator_OnStartL1Sync_Call) Run(run func(ctx context.Context)) *L1BlockCheckerIntegrator_OnStartL1Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *L1BlockCheckerIntegrator_OnStartL1Sync_Call) Return(_a0 bool) *L1BlockCheckerIntegrator_OnStartL1Sync_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *L1BlockCheckerIntegrator_OnStartL1Sync_Call) RunAndReturn(run func(context.Context) bool) *L1BlockCheckerIntegrator_OnStartL1Sync_Call {
	_c.Call.Return(run)
	return _c
}

// OnStartL2Sync provides a mock function with given fields: ctx
func (_m *L1BlockCheckerIntegrator) OnStartL2Sync(ctx context.Context) bool {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for OnStartL2Sync")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// L1BlockCheckerIntegrator_OnStartL2Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnStartL2Sync'
type L1BlockCheckerIntegrator_OnStartL2Sync_Call struct {
	*mock.Call
}

// OnStartL2Sync is a helper method to define mock.On call
//   - ctx context.Context
func (_e *L1BlockCheckerIntegrator_Expecter) OnStartL2Sync(ctx interface{}) *L1BlockCheckerIntegrator_OnStartL2Sync_Call {
	return &L1BlockCheckerIntegrator_OnStartL2Sync_Call{Call: _e.mock.On("OnStartL2Sync", ctx)}
}

func (_c *L1BlockCheckerIntegrator_OnStartL2Sync_Call) Run(run func(ctx context.Context)) *L1BlockCheckerIntegrator_OnStartL2Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *L1BlockCheckerIntegrator_OnStartL2Sync_Call) Return(_a0 bool) *L1BlockCheckerIntegrator_OnStartL2Sync_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *L1BlockCheckerIntegrator_OnStartL2Sync_Call) RunAndReturn(run func(context.Context) bool) *L1BlockCheckerIntegrator_OnStartL2Sync_Call {
	_c.Call.Return(run)
	return _c
}

// NewL1BlockCheckerIntegrator creates a new instance of L1BlockCheckerIntegrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewL1BlockCheckerIntegrator(t interface {
	mock.TestingT
	Cleanup(func())
}) *L1BlockCheckerIntegrator {
	mock := &L1BlockCheckerIntegrator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
